weight = float(input("Введите вес (кг): "))
height = float(input("Введите рост (м): "))
bmi = weight / (height * 2)
print("--- Отчет о состоянии здоровья ---")
print(f"Рост:\t{height} см\n Вес:\t {weight}")
print(f"Индекс массы тела: {bmi:.2f}")
